### ISSUE TITLE
Add some documentation and examples

### ISSUE THREAD

**Issue by mbenatti** [2trde/excrawl#1]
Hi i'm testing all lib's related to crawling, if you can put some docs and examples it will help.

Ty

**Comment by mlankenau** [comment]
Right now there are only the test cases that serve as documentation. But I will put something into the readme to get the idea what the module is doing.

**Comment by mlankenau** [comment]
Do the changes to the README help? May I close this issue?

**Comment by mbenatti** [comment]
@mlankenau You can.
thanks!
